### ISSUE TITLE
Social Media Metadata & Blog/News Support

### ISSUE THREAD

**Issue by tacc-wbomar** [TACC/CORE-cms#30]
In GitLab by @tacc-wbomar on Apr 28, 2020, 11:23

# Goal

* Figure out how to define content for social media (specifically Facebook).
* (Added: 2020-06-25) Support DjangoCMS Blog plugin (to get social media integration, but also to support blog/news).

# Background

> Facebook automatically pulls content when you include a link in the post. Ideally, this would be the title and subhead of a story, but for Texascale it's pulling a title and then the byline and link texts (the upper-left most text). Anyway to change that across the site? (probably too late, but thought I'd ask) — Aaron Dubrow

# Requirements

## Blog/News Support
1. Plugin **must** support types, categories, tags, and layouts.
1. Plugin **must** support a way to filter articles by a primary media it may contain.
1. Plugin **must** be usable enough that CMD feels comfortable training users on it (supplemental documentation is permitted).

## Social Media Metadata
1. Solution **must** support pulling article title.
1. Solution **must** support defining article description.
3. Solution **must** work for Facebook.
4. Solution **should** work for other social media.
5. (Added: 2020-06-25) Any extra functionality brought* **must** be well-tested.
6. (Added: 2020-06-25) Any extra functionality brought* **must** have known bugs **both** reported **and** documented.

# Direction

## Function

* `✓` **Django CMS plugin _to do it all_**.
    * But, do we want to add all this, now? Perhaps, a more thorough review (not just testing) of the full features of the plugin is reasonable, first.
        * (Added: 2020-06-25) Thorough review completed of [`djangocms-blog`](https://github.com/nephila/djangocms-blog).
        * (Added: 2020-06-25) Plugin bugs found have been reported, some fixed for future version of plugin.
* `?` ~~Update templates _to define `<title>` or `<meta property="og:title"…>`_.~~
    * But, how to let user set values, _instead of developer changing this for each page_?
* `?` ~~Create snippet _to let CMS user define `<meta name="description"…>` or `<meta property="og:description"…>`_.~~
    * But, how to let user set values, _instead of learning to write obtuse metadata markup_?

## Styling

* Use `s-` scope tags, because the classes are many. This is generally an easier decision than re-inventing the wheel.
* If you simply must use BEM, then use [PostCSS Modules](https://github.com/css-modules/postcss-modules) like Portal uses [CSS Modules](https://github.com/css-modules/css-modules) (as an API between BEM and components).

# Reference

- ~~[Sharing Debugger | Facebook Developers](https://developers.facebook.com/tools/debug/)~~
- ~~[Open Graph Markup](https://developers.facebook.com/docs/sharing/webmasters/#markup)~~
- [Research - Django CMS - User Guide for Blog/News](https://confluence.tacc.utexas.edu/x/rADgCQ)

# Branch

`task/24-metadata--via-djangocms-blog`

# Tasks

* [x]  research options
* [x]  test plugin
* [x]  document known issues
* [x]  resolve known issues
* [x]  ~~test ["complete social meta tag rendering"](https://github.com/nephila/djangocms-blog/issues/613#issuecomment-672012690) (see `BLOG_FB`)~~
* [x]  define how to style
* [x]  integrate knowledge from [Research - Django CMS - User Guide for Blog/News](https://confluence.tacc.utexas.edu/x/rADgCQ)

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 28, 2020, 11:39

changed title from **{-Social Media Extracting Content-}** to **{+Ensure Content Properly Displayed on Social Media+}**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 29, 2020, 12:25

changed title from **{-Ensure Content Properly Displayed on-} Social Media** to **{+Research Ways to Properly Display Content for+} Social Media**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 29, 2020, 13:24

# Plugin Research

* [`djangocms-blog`](https://github.com/nephila/djangocms-blog): social media content for blog posts via fully-featured blog ([known issues](https://github.com/nephila/djangocms-blog/issues?q=is%3Aissue+author%3Atacc-wbomar+))
* [`djangocms-page-meta`](https://github.com/nephila/djangocms-page-meta): social media content for CMS pages ([known issues](https://github.com/nephila/djangocms-page-meta/issues?q=is%3Aissue+author%3Atacc-wbomar+))

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 29, 2020, 15:40

changed title from **Research {-Ways to Properly Display Content for Social Medi-}a** to **Research {+Social Media Metadat+}a**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 29, 2020, 15:53

mentioned in commit fee0f80594205b7dd47cd4fe8081850343c1af9b

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jun 16, 2020, 16:57

changed title from **Research Social Media Metadata** to **{+PAUSED: +}Research Social Media Metadata**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jun 22, 2020, 16:58

mentioned in commit 7df978a473a02fe01f6040c3903eb77327b97caa

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jun 22, 2020, 17:03

changed title from **{-PAUSED: -}Research Social Media Metadata** to **Research Social Media Metadata**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jun 25, 2020, 15:02

The branch now has social media support via meta tags using `djangocms-blog` (which _also_ brings blog/news, tags, and categories) and `djangocms-page-meta`.

This issue has exploded in scope, _in a **good** way_. I <del>must</del> <ins>have</ins> update<ins>d</ins> it to reflect the new larger scope of its related branch. I do not feel the conflation of features, because they are all related and the diff is manageable.

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jun 25, 2020, 16:43

changed title from **{-Research Social Media Metadata-}** to **{+Social Media Metadata via Blog Plugin+}**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jun 25, 2020, 16:49

changed title from **Social Media Metadata {-via Blog Plugin-}** to **Social Media Metadata {+& Blog/News Support+}**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jul 5, 2020, 22:26

assigned to @tacc-wbomar

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Jul 17, 2020, 12:33

changed title from **Social Media Metadata & Blog/News Support** to **{+PAUSED: +}Social Media Metadata & Blog/News Support**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Aug 11, 2020, 09:50

changed title from **{-PAUSED: -}Social Media Metadata & Blog/News Support** to **Social Media Metadata & Blog/News Support**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Aug 11, 2020, 11:15

marked the task **define how to style** as completed

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Aug 11, 2020, 16:43

marked the task **integrate knowledge from [Research - Django CMS - User Guide for Blog/News](https://confluence.tacc.utexas.edu/x/rADgCQ)** as completed

**Comment by tacc-wbomar** [comment]
In GitLab by @taoteg on Sep 1, 2020, 13:05

closed via merge request !43

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Sep 1, 2020, 13:05

closed via commit 7df978a473a02fe01f6040c3903eb77327b97caa

**Comment by tacc-wbomar** [comment]
In GitLab by @taoteg on Sep 1, 2020, 13:05

mentioned in commit d4cbb77ada95692d6dd8c9d87aa8bab039701079
